# This is a basic workflow to help you get started with Actions

name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: ./
      with:
        username: 'Kuenaimaku'
        reponame: 'apple-calculator'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
